### ISSUE TITLE
failure running database migrations

### ISSUE THREAD

**Issue by nebulousdog** [TryGhost/knex-migrator#64] opened 2017-07-23 20:17 UTC
I get the following error when trying to install a local development version of ghost. 

```
~/projects/test$ ghost install local
✔ Checking system Node.js version
✔ Checking current folder permissions
ℹ Checking operating system [skipped]
ℹ Checking MySQL is installed [skipped]
✔ Checking for latest Ghost version
✔ Setting up install directory
✔ Downloading and installing Ghost v1.0.0
✔ Finishing install process
✔ Configuring Ghost
✔ Setting up instance
✖ Running database migrations
An error occurred.
Message: 'Command failed: knex-migrator-migrate --init --mgpath /home/tom/projects/test/current

null'


Debug Information:
    Node Version: v6.9.5
    Ghost-CLI Version: 1.0.0
    Environment: development
    Command: 'ghost install local'
```

I'm able to successfully install the `knex-migrator` though. Any advice would be greatly appreciated! Thanks

**Comment by acburdine** [comment] 2017-07-23 20:28
Closing this as a duplicate of TryGhost/Ghost-CLI#378

**Closed by acburdine** 2017-07-23 20:28 UTC
