### ISSUE TITLE
Concurrent migrations don't work as expected

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/knex-migrator#78] opened 2017-10-17 15:41 UTC
I've been experimenting some more to try to understand why #76 happened. I did originally think it was exacerbated by a lack of guards in the permissions relation migrations in Ghost, but the code does contain guards that make those files idempotent. Running the migrations multiple times one-after-the-other always works as expected.

----

Therefore, I tried to reproduce the duplications by running migrations multiple times concurrently. Doing this, I was able to reproduce the duplicate entries in the migrations table on MySQL, and in SQLite3 I ran into an error.

## Reproduction:

- I opened two terminal windows to the same local Ghost install.
- I removed the theme permissions entry from the migrations table in the database
- I then pasted the following command in both terminals: 
    - `DEBUG=ghost:* knex-migrator migrate --v 1.13 --force`
- And then pressed enter in both of them as fast as possible, so they ran at the same time.

**Results on MySQL**

Both migrations completed successfully, there are now duplicate rows in the migrations table, and duplicate entries in the permissions_roles table.

**Results on SQLite3**

One of the migrations completed successfully, the second one resulted in an error:

```
NAME: MigrationScript
CODE: SQLITE_BUSY
MESSAGE: insert into "migrations" ("currentVersion", "name", "version") values ('1.14', '2-theme-permissions.js', '1.13') - SQLITE_BUSY: database is locked

level:normal

Error occurred while executing the following migration: 2-theme-permissions.js
MigrationScript: insert into "migrations" ("currentVersion", "name", "version") values ('1.14', '2-theme-permissions.js', '1.13') - SQLITE_BUSY: database is locked
    at MigrationScript.KnexMigrateError (/Users/hannah/Ghost/dependencies/knex-migrator/lib/errors.js:9:26)
    at new MigrationScript (/Users/hannah/Ghost/dependencies/knex-migrator/lib/errors.js:28:26)
    at /Users/hannah/Ghost/dependencies/knex-migrator/lib/index.js:355:19
    at tryCatcher (/Users/hannah/Ghost/dependencies/knex-migrator/node_modules/bluebird/js/release/util.js:16:23)
```

## Expectations

As far as I understand it, migrations should be running in a transaction. Therefore, the database should be handling only allowing one transaction to occur at a time. The first migration should complete, and then the second one should find there is nothing to do?
At worst, the second one should hit an error trying to do something that's already done, and rollback.

**Comment by kirrg001** [comment] 2017-10-24 17:19
This looks like a database configuration problem, because i cannot reproduce.

@sebgie Is autocommit disabled on Pro?
@ErisDS Could you please set `autocommit=0` in your `my.cnf` and try again and let me know? ([how to change](https://stackoverflow.com/questions/4919332/how-to-set-autocommit-false-globally))

Autcommit means that a each statement in a transaction is **not** committed after each statement. See [innodb docs](https://dev.mysql.com/doc/refman/5.7/en/innodb-autocommit-commit-rollback.html).

**Comment by kirrg001** [comment] 2017-10-25 10:34
We have two options here:

1. Table creation statements shouldn't run within the transaction - this is super hard to determine. Imagine we execute migration scripts and a table get's created. How should knex-migrator know if a table get's created or not?

2. I can figure out how to set autocommit false only for the transaction.

**Comment by kirrg001** [comment] 2017-10-26 17:26
Tasks:

- [ ] Any migration script is able to tell the migrator that implicit commits happened. The migrator is then able to renew a transaction. This ensures a full rollback in case an implicit commit happened, which auto commits the whole transaction.

- [ ] We read lock the migration row as soon as a different process tries to execute a migration script. This ensure concurrent executions of migration scripts.

I have a working solution locally, but this needs more testing and prettier code 😋.

**Comment by kirrg001** [comment] 2017-10-31 11:56
Just for reference (popular migration tools)
- [node db migrate](https://github.com/db-migrate/mysql/blob/v1.1.10/index.js#L25) disables autocommit for migrations, but it was discussed [here](https://github.com/tgriesser/knex/issues/2290#issuecomment-340580735) that doing that has ugly sideaffects
- [sequelize](https://github.com/sequelize/sequelize/pull/5960) offers an option to disable/enable autocommit, but default is ON

I think the best option for now is to differentiate between DDL/DML statements as best as possible e.g. the first migration script in a version is able to do DDL statements if marked as. If marked, this script runs first outside of a transaction to ensure rollback can happen correct. As DDL can't be rolled back, we can offer an undo command for these scripts e.g. undo alter table.

**Comment by kirrg001** [comment] 2017-10-31 18:59
Using `autocommit` is definitely **no** option, because of the following behaviour.

```
SET autocommit=0;
INSERT into [table1] ...;
CREATE TABLE [table2];
ROLLBACK;
```

Even with disabling autocommit, the nature of DDL and MySQL autocommits the insert. This statement combination can happen when dealing with migrations and therefor it's a 100% none solution. 

In Ghost we always have to ensure that if you are on version 1.0 and you download 1.5 which contains a couple of migration scripts. If an error occurs, we have to rollback the changes. All of them. Because the blog get's rolled back to 1.0.

This works similar in knex migrate and sequelize, but you have to explicit call `tool rollback` in the shell, which we we would like to avoid. Knex-migrator will auto-rollback the changes.

The conclusion here is that each migration script **must** implement a rollback function. It's similar to a down function, but a down function is not automatically called when an error occurs.

So each script runs in a single transaction to allow multiple queries (but no mixture of DDL/DML) and if an error occurs in any state, we rollback previous committed changes. 

e.g. 
- you are on 1.1
- 1.2 + 1.3 are available
- you run the migrations
- 1.2 finishes, committed
- 1.3 errors, we rollback 1.2
- you are back on 1.1
- if the process dies in 1.3, the migration lock will ensure that you have to repair your data (the health check will ensure that you will receive a lock error)

By that we can ensure that a full rollback happens. There is no other way with MySQL!
I need some more time to make this change happening.

**FYI: The migration lock is already implemented, but i need would like to first merge the DDL problem.**. The [task list](https://github.com/TryGhost/knex-migrator/issues/78#issuecomment-339739161) is still valid.

**Closed** 2017-11-02 23:36 UTC
Labels: bug, feature
