### ISSUE TITLE
"ER_TOO_LONG_KEY: Specified key was too long" false error

### ISSUE THREAD

**Issue by BlueHatbRit** [TryGhost/knex-migrator#51] opened 2017-02-03 15:33 UTC
First of all, thanks for the module it's making migrations really easy to run especially with the cli executable.

## Issue description
I have a string column with a maxlength of 254, when running `knex-migrator init` I get the error below, however if I re-run the command a second time then it succeeds. I've provided the full error code that seems to be popping out, the offending column definition and a quick sample I object made to help test and resolve the issue.

I'd be happy to have a look at submitting a fix if someone is able to provide a bit of initial direction on where the think the issue might be. Otherwise I'll just be digging through the code by hand which might be quite slow!

## Error message
`ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes`

## Offending column definition
```javascript
email: {type: 'string', maxlength: 254, nullable: false, unique: true}
```

## Larger sample
```javascript
users: {
        id: {type: 'increments', nullable: false, primary: true},
        email: {type: 'string', maxlength: 254, nullable: false, unique: true},
        password: {type: 'string', maxlength: 60, nullable: false},
        created_at: {type: 'dateTime', nullable: false},
        updated_at: {type: 'dateTime', nullable: false}
    }
```

**Comment by kirrg001** [comment] 2017-02-03 15:37
Hey @BlueHatbRit 👋

Right now `knex-migrator` hardcodes the database encoding, see https://github.com/TryGhost/knex-migrator/blob/master/lib/database.js#L25.
`utf8mb4` has the requirement that all unique keys and indexes must have the length of 191 characters, see https://dev.mysql.com/doc/refman/5.7/en/charset-unicode-conversion.html

`knex-migrator` has to read the database encoding from the user and define a fallback.
If you would like to PR this change, tell me 👍

**Comment by BlueHatbRit** [comment] 2017-02-03 15:57
Hi @kirrg001, looks simple enough. Should be able to check if options object has a definition and use that, if not then fall back to `utf8mb4` as already defined.

I'll give it a crack this evening. Any idea why this might be happening on the first call and not the second? I'm just interested in what might be different the second time around, I'm assuming there's no roll-back or something which causes the issue.

**Comment by kirrg001** [comment] 2017-02-03 16:39
> Should be able to check if options object has a definition and use that, if not then fall back to utf8mb4 as already defined.

👍 

> I'll give it a crack this evening. Any idea why this might be happening on the first call and not the second? I'm just interested in what might be different the second time around, I'm assuming there's no roll-back or something which causes the issue.

Yeah that is a good question. When `knex-migrator` executes the init scripts and an error occurs, it always rolls back any change. Could you please share your init scripts?

**Comment by kirrg001** [comment] 2017-02-03 16:59
I can reproduce it locally, no need to share your script 👍 
Will look into now.

**Comment by kirrg001** [comment] 2017-02-03 17:23
In MySQL `alter table` or `create tables` operations can't roll back. It's marked as feature request in MySQL.

https://bugs.mysql.com/bug.php?id=28727
http://stackoverflow.com/questions/4692690/is-it-possible-to-roll-back-create-table-and-alter-table-statements-in-major-sql

So if `ER_TOO_LONG_KEY` occurs, MySQL creates the affected field with the defined length although an error occurred. In your case `email` with 254 characters - **but without unique constraint**!

I will add a condition for this error code and log a little how-to-fix text when this happens.

In your case: this only happened to you, because `utf8mb4` was hardcoded by accident 👍 
Thanks for your help and your upcoming PR :)

**Closed** 2017-02-04 11:35 UTC
Labels: bug

**Comment by kevinansfield** [comment] 2020-08-10 18:36
## Solving this problem when you hit it

[Ghost](https://ghost.org) recently introduced some indexes that will trigger this error so I thought it would be useful to add some documentation here to cover how to upgrade/"fix" your database when you hit this error.

You're most likely to run into this error on MySQL 5.6 or earlier, if you've upgraded from those versions to 5.7, or if you've made changes to your MySQL config for backwards compatibility with older databases/software. Specifically you need to have `innodb_large_prefix` variable set to ON and have the supporting variables and file/row formats - MySQL docs for this variable are here https://dev.mysql.com/doc/refman/5.6/en/innodb-parameters.html#sysvar_innodb_large_prefix.

With Ghost, you'll run into the error during installation or upgrade with a message that looks something like this (the `customer_id` and `members_stripe_customers` parts could be different):

```
Field length of `customer_id` in `members_stripe_customers` is too long!
```

This error will occur with the default MySQL configuration found in MySQL 5.5 or 5.6 and potentially with databases that were created in those versions and later upgraded to MySQL 5.7. The underlying cause is related to the length of indexes that are available in earlier MySQL versions.

To resolve the problem it's necessary to modify your database config and potentially update tables to use a different row format. It's also recommended to upgrade to MySQL 5.7 if you are on an earlier version.

On the config side, ensure that your database has the variables below set with the expected values. You can check these by running the query `show variables like "innodb%";`

```
innodb_large_prefix=ON;
innodb_file_per_table=ON;
innodb_file_format=Barracuda;
```

If the config does not match the above you can change your MySQL config, typically via the `my.cnf` file in `/etc/` or `/etc/mysql/`:

```
[mysqld]
innodb_file_per_table=ON
innodb_file_format=Barracuda
innodb_large_prefix=ON
# The next setting is optional, it ensures future tables will support indexes of a larger size
innodb_default_row_format = 'DYNAMIC'
```

Remember to restart your MySQL server after any config changes.

Finally, it's necessary to ensure that any tables with large indexed fields are using a supported row format. To view the row format for the tables in your database, run the following query (replace $DB_NAME with your database):

```sql
SELECT TABLE_NAME, ROW_FORMAT FROM information_schema.TABLES WHERE TABLE_SCHEMA="$DB_NAME" AND ROW_FORMAT != 'DYNAMIC' AND ROW_FORMAT != 'COMPRESSED';
```

If the result set is empty there's nothing left to do, you can retry your installation or upgrade.

However, if you get any results back that means you have some tables that require updating to use innodb's later file/row format. Running the following query will generate a list of MySQL commands that need to be copy/pasted one at a time to update each table (replace $DB_NAME with your database):

```sql
USE information_schema;
SELECT CONCAT("ALTER TABLE `", TABLE_SCHEMA, "`.`", TABLE_NAME, "` ROW_FORMAT=DYNAMIC;") AS MySQLCMD FROM TABLES WHERE ENGINE='innodb' AND ROW_FORMAT != 'DYNAMIC' AND ROW_FORMAT != 'COMPRESSED' AND TABLE_SCHEMA="$DB_NAME";
```

Re-run the select query once finished to double-check that all tables were updated, the result set should be empty (replace $DB_NAME with your database):

```sql
SELECT TABLE_NAME, ROW_FORMAT FROM information_schema.TABLES WHERE TABLE_SCHEMA="$DB_NAME" AND ROW_FORMAT != 'DYNAMIC' AND ROW_FORMAT != 'COMPRESSED';
```

If the result set is empty you've finished, you can retry your installation or upgrade, or retry your original ALTER TABLE statement to add indexes if you hit this error outside of using Ghost.

**Comment by LukeTully** [comment] 2020-08-15 02:23
@kevinansfield Thanks for the incredible addition to this thread.

**Comment by huixisheng** [comment] 2020-09-05 07:04
my mysql version is 5.7.26
but run with error
```
by-ghost    | [2020-09-05 07:04:05] INFO Creating table: members_labels
by-ghost    | [2020-09-05 07:04:05] INFO Creating table: members_stripe_customers
by-ghost    | [2020-09-05 07:04:05] ERROR Field length of `customer_id` in `members_stripe_customers` is too long!
by-ghost    | 
by-ghost    | Field length of `customer_id` in `members_stripe_customers` is too long!
by-ghost    | 
by-ghost    | "This usually happens if your database encoding is utf8mb4.\nAll unique fields and indexes must be lower than 191 characters.\nPlease correct your field length and reset your database with knex-migrator reset.\n"
by-ghost    | "Read more here: https://github.com/TryGhost/knex-migrator/issues/51\n"
by-ghost    | 
by-ghost    | Error ID:
by-ghost    |     300
by-ghost    | 
by-ghost    | Error Code: 
by-ghost    |     ER_TOO_LONG_KEY
by-ghost    | 
by-ghost    | ----------------------------------------
by-ghost    | 
by-ghost    | MigrationScriptError: Field length of `customer_id` in `members_stripe_customers` is too long!
by-ghost    |     at MigrationScriptError.KnexMigrateError (/var/lib/ghost/versions/3.31.5/node_modules/knex-migrator/lib/errors.js:7:26)
by-ghost    |     at new MigrationScriptError (/var/lib/ghost/versions/3.31.5/node_modules/knex-migrator/lib/errors.js:25:26)
by-ghost    |     at /var/lib/ghost/versions/3.31.5/node_modules/knex-migrator/lib/index.js:1045:23
by-ghost    | 
by-ghost    | Error: ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes
by-ghost    |     at Query.Sequence._packetToError (/var/lib/ghost/versions/3.31.5/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
by-ghost    |     at Query.ErrorPacket (/var/lib/ghost/versions/3.31.5/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
by-ghost    |     at Protocol._parsePacket (/var/lib/ghost/versions/3.31.5/node_modules/mysql/lib/protocol/Protocol.js:291:23)
by-ghost    |     at Parser._parsePacket (/var/lib/ghost/versions/3.31.5/node_modules/mysql/lib/protocol/Parser.js:433:10)
by-ghost    |     at Parser.write (/var/lib/ghost/versions/3.31.5/node_modules/mysql/lib/protocol/Parser.js:43:10)
by-ghost    |     at Protocol.write (/var/lib/ghost/versions/3.31.5/node_modules/mysql/lib/protocol/Protocol.js:38:16)
by-ghost    |     at Socket.<anonymous> (/var/lib/ghost/versions/3.31.5/node_modules/mysql/lib/Connection.js:88:28)
by-ghost    |     at Socket.<anonymous> (/var/lib/ghost/versions/3.31.5/node_modules/mysql/lib/Connection.js:526:10)
by-ghost    |     at Socket.emit (events.js:315:20)
by-ghost    |     at addChunk (_stream_readable.js:295:12)
by-ghost    |     at readableAddChunk (_stream_readable.js:271:9)
by-ghost    |     at Socket.Readable.push (_stream_readable.js:212:10)
by-ghost    |     at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
by-ghost    |     --------------------
by-ghost    |     at Protocol._enqueue (/var/lib/ghost/versions/3.31.5/node_modules/mysql/lib/protocol/Protocol.js:144:48)
by-ghost    |     at Connection.query (/var/lib/ghost/versions/3.31.5/node_modules/mysql/lib/Connection.js:198:25)
by-ghost    |     at /var/lib/ghost/versions/3.31.5/node_modules/knex-migrator/node_modules/knex/lib/dialects/mysql/index.js:135:18
by-ghost    |     at Promise._execute (/var/lib/ghost/versions/3.31.5/node_modules/bluebird/js/release/debuggability.js:384:9)
by-ghost    |     at Promise._resolveFromExecutor (/var/lib/ghost/versions/3.31.5/node_modules/bluebird/js/release/promise.js:518:18)
by-ghost    |     at new Promise (/var/lib/ghost/versions/3.31.5/node_modules/bluebird/js/release/promise.js:103:10)
by-ghost    |     at Client_MySQL._query (/var/lib/ghost/versions/3.31.5/node_modules/knex-migrator/node_modules/knex/lib/dialects/mysql/index.js:129:12)
by-ghost    |     at Client_MySQL.query (/var/lib/ghost/versions/3.31.5/node_modules/knex-migrator/node_modules/knex/lib/client.js:169:17)
by-ghost    |     at Runner.query (/var/lib/ghost/versions/3.31.5/node_modules/knex-migrator/node_modules/knex/lib/runner.js:151:36)
by-ghost    |     at Runner.queryArray (/var/lib/ghost/versions/3.31.5/node_modules/knex-migrator/node_modules/knex/lib/runner.js:248:31)
by-ghost    |     at async /var/lib/ghost/versions/3.31.5/node_modules/knex-migrator/node_modules/knex/lib/runner.js:277:18
by-ghost    | 
```

**Comment by perpetuallight** [comment] 2022-06-20 01:33
Am I correct in assuming this meant to raise the barrier for self hosting specs/environments? To the exclusion of a managed DBaaS? For instance a free tier ClearDB integration...



> ## Solving this problem when you hit it
> [Ghost](https://ghost.org) recently introduced some indexes that will trigger this error so I thought it would be useful to add some documentation here to cover how to upgrade/"fix" your database when you hit this error.
> 
> You're most likely to run into this error on MySQL 5.6 or earlier, if you've upgraded from those versions to 5.7, or if you've made changes to your MySQL config for backwards compatibility with older databases/software. Specifically you need to have `innodb_large_prefix` variable set to ON and have the supporting variables and file/row formats - MySQL docs for this variable are here https://dev.mysql.com/doc/refman/5.6/en/innodb-parameters.html#sysvar_innodb_large_prefix.
> 
> With Ghost, you'll run into the error during installation or upgrade with a message that looks something like this (the `customer_id` and `members_stripe_customers` parts could be different):
> 
> ```
> Field length of `customer_id` in `members_stripe_customers` is too long!
> ```
> 
> This error will occur with the default MySQL configuration found in MySQL 5.5 or 5.6 and potentially with databases that were created in those versions and later upgraded to MySQL 5.7. The underlying cause is related to the length of indexes that are available in earlier MySQL versions.
> 
> To resolve the problem it's necessary to modify your database config and potentially update tables to use a different row format. It's also recommended to upgrade to MySQL 5.7 if you are on an earlier version.
> 
> On the config side, ensure that your database has the variables below set with the expected values. You can check these by running the query `show variables like "innodb%";`
> 
> ```
> innodb_large_prefix=ON;
> innodb_file_per_table=ON;
> innodb_file_format=Barracuda;
> ```
> 
> If the config does not match the above you can change your MySQL config, typically via the `my.cnf` file in `/etc/` or `/etc/mysql/`:
> 
> ```
> [mysqld]
> innodb_file_per_table=ON
> innodb_file_format=Barracuda
> innodb_large_prefix=ON
> # The next setting is optional, it ensures future tables will support indexes of a larger size
> innodb_default_row_format = 'DYNAMIC'
> ```
> 
> Remember to restart your MySQL server after any config changes.
> 
> Finally, it's necessary to ensure that any tables with large indexed fields are using a supported row format. To view the row format for the tables in your database, run the following query (replace $DB_NAME with your database):
> 
> ```sql
> SELECT TABLE_NAME, ROW_FORMAT FROM information_schema.TABLES WHERE TABLE_SCHEMA="$DB_NAME" AND ROW_FORMAT != 'DYNAMIC' AND ROW_FORMAT != 'COMPRESSED';
> ```
> 
> If the result set is empty there's nothing left to do, you can retry your installation or upgrade.
> 
> However, if you get any results back that means you have some tables that require updating to use innodb's later file/row format. Running the following query will generate a list of MySQL commands that need to be copy/pasted one at a time to update each table (replace $DB_NAME with your database):
> 
> ```sql
> USE information_schema;
> SELECT CONCAT("ALTER TABLE `", TABLE_SCHEMA, "`.`", TABLE_NAME, "` ROW_FORMAT=DYNAMIC;") AS MySQLCMD FROM TABLES WHERE ENGINE='innodb' AND ROW_FORMAT != 'DYNAMIC' AND ROW_FORMAT != 'COMPRESSED' AND TABLE_SCHEMA="$DB_NAME";
> ```
> 
> Re-run the select query once finished to double-check that all tables were updated, the result set should be empty (replace $DB_NAME with your database):
> 
> ```sql
> SELECT TABLE_NAME, ROW_FORMAT FROM information_schema.TABLES WHERE TABLE_SCHEMA="$DB_NAME" AND ROW_FORMAT != 'DYNAMIC' AND ROW_FORMAT != 'COMPRESSED';
> ```
> 
> If the result set is empty you've finished, you can retry your installation or upgrade, or retry your original ALTER TABLE statement to add indexes if you hit this error outside of using Ghost.
